use_frameworks!

platform :ios, '10.0'

target 'REIAnalyticsKit_Example' do
  
  pod 'ACPTarget', '~> 2.1'
  pod 'ACPAnalytics', '~> 2.0'
  pod 'ACPCore', '~> 2.0'
  pod 'ACPUserProfile', '~> 2.0'
  
  pod 'NewRelicAgent'
  
  pod 'REIAnalyticsKit', :path => '../'

  target 'REIAnalyticsKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
