use_frameworks!

platform :ios, '8.0'

target 'REIAnalyticsKit_Example' do
  pod 'REIAnalyticsKit', :path => '../'

  target 'REIAnalyticsKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
